swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
      # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /account/transaction/{month}:   
    get:
      tags: 
        - Transaction Module
      summary: Find transactions for each account for current month  
      description: Returns the list of transactions for current month
      parameters:
        - in: path
          name: month
          description: Information of transactions to return 
          required: true
          type : string
      produces:
        - application/json
      responses:
        '200':
          description: User transactions recovered successfully
          schema:
            $ref: '#/definitions/TransactionsofMonth'
        '400':
          description: transaction not found
        '500':
          description: Internal Server Error
      security:
        - Bearer: []
  /transaction/{id}:
    get:
      tags:
        - Transaction Module 
      summary: Find transaction by ID
      description: Returns a single transaction
      operationId: getTransactionById
      parameters:
        - in: path 
          name: id
          description: ID of transaction to return
          required: true
          type : string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction ID retrieved successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid ID supplied
        '500':
          description: Internal Server Error
      security:
        - Bearer: []
  /transaction:
    put:
      tags:
        - Transaction Module
      summary: Update transaction
      description: category or note that needs to be modified
      parameters:
        - in: body 
          name: body
          required: true
          schema:
            $ref: '#/definitions/UpdateTransaction'
      produces:
        - application/json
      responses:
        '200':
          description: Update an existing transaction in the account
          schema:
            $ref: '#/definitions/UpdateTransaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
      security:
        - Bearer: []
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  TransactionsofMonth:
    type: object
    properties:
      month:
        type: string
      id : 
        type: string
      type : 
        type: string
  Transaction:
    type: object
    properties:
      id:
        type: string
      date : 
        type: number
      description : 
        type: string
      amount : 
        type: number
      balance : 
        type : number
  UpdateTransaction:
    type: object
    properties:
      category:
        type: string
      note : 
        type: string 
